export const ADD_DEVIS_REQUEST = 'ADD_DEVIS_REQUEST'
export const ADD_DEVIS_SUCESS = 'ADD_DEVIS_SUCESS'
export const ADD_DEVIS_FAIL = 'ADD_DEVIS_FAIL'

// delete devis
export const DEL_DEVIS_REQUEST = 'DEL_DEVIS_REQUEST'
export const DEL_DEVIS_SUCESS = 'DEL_DEVIS_SUCESS'
export const DEL_DEVIS_FAIL = 'DEL_DEVIS_FAIL'

// delete devis by client
export const DEL_DEVIS_CLIENT_REQUEST = 'DEL_DEVIS_CLIENT_REQUEST'
export const DEL_DEVIS_CLIENT_SUCESS = 'DEL_DEVIS_CLIENT_SUCESS'
export const DEL_DEVIS_CLIENT_FAIL = 'DEL_DEVIS_CLIENT_FAIL'
