export const CALANDER_REQUEST='CALANDER_REQUEST'
export const CALANDER_SUCCESS='CALANDER_SUCCESS'
export const CALANDER_FAIL='CALANDER_FAIL'

export const ETAT_DEVIS_REQUEST='ETAT_DEVIS_REQUEST'
export const ETAT_DEVIS_SUCCESS='ETAT_DEVIS_SUCCESS'
export const ETAT_DEVIS_FAIL='ETAT_DEVIS_FAIL'